name: Test
on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  test:
    # IMPORTANT: prevent this action from running on forks
    if: github.repository == 'Cryptic-Dot/tuna-backend-sdk'
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.x"]
    environment: "Development"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
        env:
          RPC_URL: ${{ secrets.RPC_URL }}